[theme]
primaryColor = "#4A90E2"              # Azul institucional leve
backgroundColor = "#ffffff"           # Branco
secondaryBackgroundColor = "#f7f7f7"  # Cinza claro
textColor = "#262730"                 # Quase preto
font = "sans serif"
